# Train PSNR-oriented AdaTarget on DF2K_OST dataset with blind degradation settings
name: AdaTarget_DF2K_OST_Blind_x4
model_type: AdaTarget_Model
scale: 4
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0

k_size: 7
s_size: 9

# ----------------- options for synthesizing training data----------------- #
# USM the ground-truth
l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: False

Use_sharpen: True

pre_pad: 0
tile_size: 480
tile_pad: 24
tile_process: False

# the first degradation process
resize_prob: [0.1, 0.85, 0.05]  # up, down, keep
resize_range: [0.8, 1.2]
gaussian_noise_prob: 0.5
noise_range: [1, 12]
poisson_scale_range: [0.05, 0.8]
gray_noise_prob: 0.2
jpeg_range: [75, 95]

gt_size: 140
queue_size: 180

# dataset and data loader settings
datasets:
  train:
    name: DF2K_OST
    type: OneStageDegradation_DF2K_Dataset
    dataroot_all_gt: /home/chendu/data2_hdd10t/chendu/dataset/DF2K_OST/subimages_512 #path to DF2K_OST training dataset or your own training dataset

    blur_kernel_size_min: 1
    blur_kernel_size_max: 4
    kernel_list: ['iso', 'aniso']
    kernel_prob: [0.7, 0.3]
    sinc_prob: 0.01
    blur_sigma: [0.1, 1.0]
    betag_range: [0.1, 2.0]
    betap_range: [0.1, 1.0]

    gt_size: 140
    use_hflip: True
    use_rot: False

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Test/GT/Set5 #path to your own testing dataset, we also provide our validation GT dataset in "datasets/Test/GT/Set5"
    dataroot_lq: datasets/Test/Blind_Degradation_Benchmark_LQ/Set5 #path to your own testing dataset, we also provide our validation LQ dataset in "datasets/Test/Blind_Degradation_Benchmark_LQ/Set5"
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBAdaNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
  gc: 32

network_loc:
  type: LocNet

#The pretrained model is provided by the AdaTarget paper, which is trained on bicubic degradation without a discriminator. https://github.com/yhjo09/AdaTarget
load_mode_g: original
path:
  pretrain_network_g: experiments/pretrained_models/AdaTarget-GAN/Bicubic_PSNR/RRDB_PSNR_x4.pth

load_mode_loc: original
path_loc:
  pretrain_network_loc: experiments/pretrained_models/AdaTarget-GAN/Bicubic_PSNR/LocNet_TR.pth

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_loc:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.1

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  adatarget_opt:
    type: AdaTargetLoss
    loss_weight: !!float 1.0

# Uncomment these for validation
# validation settings
val:
 val_freq: !!float 5e4
 save_img: True

 metrics:
   psnr: # metric name
     type: calculate_psnr
     crop_border: 4
     test_y_channel: false
   ssim: # metric name
     type: calculate_ssim
     crop_border: 4
     test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
